### ISSUE TITLE
missing a library

### ISSUE THREAD

**Issue by meysam9323** [nitishsrivastava/deepnet#1]
Hi Nitish,

Thanks for putting up the code.
I tried to run setup_examples.py; however, it seems that  deepnet.py is missing in the package. Can you please check that out?

Here is the error:
Traceback (most recent call last):
  File "setup_examples.py", line 2, in <module>
    from deepnet import util
ImportError: No module named deepnet

Thanks,
-M

**Comment by nitishsrivastava** [comment]
Is deepnet on your PYTHONPATH?

**Comment by meysam9323** [comment]
Just added the path and works fine now!
thanks.

**Comment by iBM88** [comment]
I have the same issue; I added deepnet to PYTHONPATH as:
    export PYTHONPATH=$PYTHONPATH:$HOME/deepnet
I checked it by:
    echo $PYTHONPATH
and
    for p in sys.path: print p
But when I run 
    python setup_examples.py
I still get the same error:
    Traceback (most recent call last):
      File "setup_examples.py", line 2, in <module>
        from deepnet import util
    ImportError: No module named deepnet

Any suggestions?

**Comment by theoryno3** [comment]
You'll need to place deepnet's parent folder in the PYTHONPATH. In your
case,  place it not in your home folder, but something like
$HOME/libraries/deepnet. Then append "$ HOME/libraries" to your PYTHONPATH.

**Comment by iBM88** [comment]
Thanks, this seems working.

**Comment by PhoenixLuo2** [comment]
hi everyone,I have the same issue,i refer to the answer that edit the PYTHONPATH as fellow:

# for deepnet

export PYTHONPATH=/home/llx/codes/deepnet
export PYTHONPATH=/home/llx/codes/deepnet/deepnet
export PYTHONPATH=${PYTHONPATH}:/home/llx/codes/deepnet/cudamat
export PATH=$PATH:/home/llx/codes/deepnet/cudamat
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/llx/codes/deepnet/cudamat

unfortunately,issue still remain,Any suggestions?
