### ISSUE TITLE
a bug & some question

### ISSUE THREAD

**Issue by fqhlxw520** [nitishsrivastava/deepnet#10]
My Nvidia display card is old GT9800, your trainer.py code I change it like that

def LockGPU(max_retries=10):
    cm.cublas_init()

so that I can run it.

I do an experiment on small norb that I first resize all the image to 32x32 and the test data and validation data I make them point to all the same test file. Here is my result on dbn modal.
E_CE: 0.000 E_Acc: 0.000 (0/1000) E_CE: 18.559 E_Acc: 0.200 (199/1000)
I have read your code several times and my question is why the evaluate result on validation data and test data are different even though they point to the same data bunch?

**Comment by fqhlxw520** [comment]
Besides how can I improve the prediction rate or cut the error rate on the dbn modal? No matter how many steps I train on the file( two layer, learning rate 0.01, 1024 hidden node, other parameter is the same like you) and no matter what training alg I use, the prediction rate are always 0.2. I have also train on the rbm modal and dbm modal that I follow Hinton's rbm train guide with your code, the result is not so satisfied. I hope you can give some useful suggestion.

**Comment by nitishsrivastava** [comment]
Could you post your model, training and data pbtxt files?

**Comment by fqhlxw520** [comment]
here is my model and figure save from visualise.py

------------------ 原始邮件 ------------------
发件人: "Nitish Srivastava"notifications@github.com;
发送时间: 2013年3月13日(星期三) 凌晨1:05
收件人: "nitishsrivastava/deepnet"deepnet@noreply.github.com; 
抄送: "fqhlxw520"1123736732@qq.com; 
主题: Re: [deepnet] a bug & some question (#10)

Could you post your model pbtxt files?

**Comment by fqhlxw520** [comment]
sorry for mistake, I have already post on my github https://github.com/fqhlxw520/deepnet.git. I'm green hand for the github and don't know how to push to your branch. The model and some figure are under the deepnet/example fold which named "norb_rbm" and "norb_dbn"

**Comment by nitishsrivastava** [comment]
In norb_rbm: You should use linear input units instead of logistic units because the input is real-valued. Also, it is useful to mean center and standardize the data. Let me know if you still have problems after fixing this.

**Comment by fqhlxw520** [comment]
It's grate! It works! Thanks you very much! I delete the model files and rebuild it, now it can reach to 61.5% prediction accuracy. But I don't think it's satisfied. I wanna get more higher accuracy and will do more experiments. But I still have questions. First, how to choose the activation unit? You have 7 unit can choose to activate the unit and 4 train method to optimize if my deep net are n layer, the total proper combination number of units will grow exponentially(4 to the power 7 to the power n). And the second question is do you depend on the numerous train steps(such as your demo shows that 100000 steps) to guarantee the high accuracy?

**Comment by nitishsrivastava** [comment]
Please see http://www.cs.toronto.edu/~hinton/absps/guideTR.pdf to learn how to train RBMs.

**Comment by fqhlxw520** [comment]
Sorry for mistake, my result is not activate on the linear unit for rbm but for the classify layer. I'm so careless, sorry.  I'm train on dbn, the data has been 0 mean no unit variance, and the linear unit for the classify layer is really work(no matter the first rbm train with logistic or tanh, the test accuracy result are always 60%~70%, and train accuracy can reach to 85%  with 20000 train steps, on the while, softmax not work for the classify layer, error said incompatible matrix). When I normalise the data to 0 mean and unit variance , and start train with linear unit for the first rbm, error occur like that:
RBM 1
Step 50  T_sp: -2214618533321123087515648.000 T_E: 772.18486 E_E: nan
Step 100  T_sp: nan T_E: nan E_E: nan
Traceback (most recent call last):
  File "../../trainer.py", line 68, in <module>
    main()
  File "../../trainer.py", line 63, in main
    model.Train()
  File "/home/chase/deepnet/deepnet/neuralnet.py", line 530, in Train
    self.Show()
  File "/home/chase/deepnet/deepnet/neuralnet.py", line 445, in Show
    layer.Show()
  File "/home/chase/deepnet/deepnet/dbm_layer.py", line 41, in Show
    visualize.display_hidden(self.pos_state.asarray(), self.fig_neg, title=self.name + "_positive")
  File "/home/chase/deepnet/deepnet/visualize.py", line 31, in display_hidden
    plt.hist(state.mean(axis=1), 100)
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 2160, in hist
    ret = ax.hist(x, bins, range, normed, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, *_kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 7668, in hist
    m, bins = np.histogram(x[i], bins, weights=w[i], *_hist_kwargs)
  File "/usr/lib/pymodules/python2.7/numpy/lib/function_base.py", line 148, in histogram
    'max must be larger than min in range parameter.')
AttributeError: max must be larger than min in range parameter.

Could you post your model files for the norb?
