### ISSUE TITLE
Error 127 while 'sudo make' cudamat

### ISSUE THREAD

**Issue by TianCuan** [nitishsrivastava/deepnet#101]
i met 'Error 127' while running make in cudamat dir.  The command i type is 'sudo make'. and get this result:

nvcc -O3 \
    -v \
    -gencode=arch=compute_10,code=sm_10 \
  -gencode=arch=compute_20,code=sm_20 \
    -gencode=arch=compute_30,code=sm_30 \
    --compiler-options '-fPIC' -o libcudamat.so \
    --shared cudamat.cu cudamat_kernels.cu -lcublas -L
make: nvcc: Command not found
Makefile:5: recipe for target 'libcudamat.so' failed
make: **\* [libcudamat.so] Error 127

why this happened? how can i solve it?
thank you~

**Comment by TianCuan** [comment]
Delete the row:-gencode=arch=compute_10,code=sm_10 \
May help.

**Comment by struggling-man** [comment]
I have the same trouble as you， but delete the row is not resloved.  Can you help me? Thank you!
