### ISSUE TITLE
Model for Convolutional network

### ISSUE THREAD

**Issue by phvu** [nitishsrivastava/deepnet#12]
Maybe I missed something, but could you provide a simple example on how to write a pbtxt file for training a convolutional NN? I think it is supported (since prontos/deepnet.proto has some parameters for that) but I have some doubts, like should I have Parameter.Convolution in a Layer or in Edge, and in that case, what should be the name for the parameter etc... I think a simple example would clear those doubts.
Btw, with some minor changes in Make script and CUDA code, I managed to compile the code successfully on CUDA 5. I can send you the modified code (or a description about what have been changed), if it is needed.

Thank you for making this awesome library be available.

**Comment by nitishsrivastava** [comment]
I have added an example for convolutional nets now. I would be great if you can post a description of the modifications for CUDA 5 on the deepnet wiki. That way other users can use it too!

**Comment by lzamparo** [comment]
@phvu, @nitishsrivastava: can either of you unpack which Makefile target "make $*" (in the last line of build.sh) actually references?  I've never encountered this before and don't see what target it invokes in the Makefile.

Thanks,
