### ISSUE TITLE
questions for convolution pbtxt files

### ISSUE THREAD

**Issue by fqhlxw520** [nitishsrivastava/deepnet#15]
Your convolution demo are perfectly fit the result(90% only need 100 train steps). But I don't know some parameter means such as 
  # nloc = (x_width + 2_padding - size)/stride + 1
  #  = (28 + 2_ 2- 5)/1 + 1 = 28
Is this a convolution layer or sample layer? Like LeNet series deep network, the first convolution layer size would be 24*24, if it's conv layer, why the size not change? It's a little hard to understand your comment, maybe you can give me what paper you refer to. Also, like the layer type, what does the parameter "shape" and "receptive_field_width" mean? I'm afraid Hinton's training guide have not mentioned it.

When I tried to change the configure file to fit the LeNet. I only change the num_filters in the hidden1 layer, the error occur like that:
Traceback (most recent call last):
  File "../../trainer.py", line 67, in <module>
    main()
  File "../../trainer.py", line 62, in main
    model.Train()
  File "/home/chase/deepnet/deepnet/neuralnet.py", line 522, in Train
    self.SetUpTrainer()
  File "/home/chase/deepnet/deepnet/neuralnet.py", line 482, in SetUpTrainer
    self.LoadModelOnGPU()
  File "/home/chase/deepnet/deepnet/neuralnet.py", line 115, in LoadModelOnGPU
    self.edge.append(self.EdgeClass(edge, node1, node2))
  File "/home/chase/deepnet/deepnet/edge.py", line 34, in **init**
    self.LoadParams()
  File "/home/chase/deepnet/deepnet/edge.py", line 298, in LoadParams
    n_locs = self.AllocateMemoryForConvolutions(param, node1, node2)
  File "/home/chase/deepnet/deepnet/edge.py", line 243, in AllocateMemoryForConvolutions
    assert numdims % num_colors == 0
AssertionError

Is it a bug?

**Comment by nitishsrivastava** [comment]
There is no bug. If you change the width of the receptive field of the filter from 5 to 24, the number of hidden units is going to change. You need to update that. The comments show how to compute the number of hidden units. The 'shape' parameter specifies the shape of the input (for example, 28 x 28 x 1, or 32 x 32 x 3, etc).

**Comment by fqhlxw520** [comment]
Actually if you change the num_filters  to 8 in the edge contain "input_layer" and "hidden1" it will error. But if change to 16,32 and modified the corresponding dimensions in layer1 it will work. I guess it maybe because the filter_acts.cu cannot load less than certain quantity data. But that's ok, it doesn't matter.

I can understand the shape represent for the input, but how about the hidden layer?
in the dbn demo ,mnist_rbm2.pbtxt 
  name: "hidden2"
  dimensions: 1024
  shape: 32
  shape: 16
In this file, the shape is 32x16. why is the shape size not equal to dimensions? Is it stand for the fan-in and fan-out size?

And I grep recursively the total project with vim and find that the receptive_field_width are only appear in the edge.py and the prototype file, it seems work for the visualization. How does it change the number of hidden units?
