### ISSUE TITLE
Bug in DataHandler

### ISSUE THREAD

**Issue by phvu** [nitishsrivastava/deepnet#18]
Hi,
I think I found a bug in DataHandler which involves dealing with multiple data files. It is in GPUCache.Get():

``` python
  def Get(self, batchsize, get_last_piece=False):
    """Return 'batchsize' data points from the cache.

    May return fewer points towards the end of the dataset when there are fewer
    than batchsize left.
    """
    skip = False
    if self._pos == self.datasize:
      self._pos = 0
      self.empty = True         # This line: load the next batch. 
    if self._pos == 0:
      if self.empty or self._maxpos < self.parent._maxpos:
        self.LoadData()
        self.empty = False
      if self.randomize and self._maxpos == self.parent._maxpos:
        # Shuffle if randomize is True and parent has not already shuffled it.
        self.ShuffleData()
    start = self._pos
    end = self._pos + batchsize
    if end > self.datasize:
      end = self.datasize
      skip = not get_last_piece
    self._pos = end
    if skip:
      return self.Get(batchsize, get_last_piece=get_last_piece)
    else:
      batch = [d.slice(start, end) for d in self.data]
      for i in range(self.num_data):
        if self.add_noise[i]:
          self.AddNoise(batch, i)
        if self.translate[i]:
          self.TranslateData(batch, i)
      return batch
```

Should the 10th line be there? Because without that, the code will never load the next files into the cache, and therefore it just reuses the already loaded data.
Please confirm if this is a bug, since I am using the 10th line as a fix...

**Comment by nitishsrivastava** [comment]
There is no bug. The 10th line in your code is not necessary as long as the main memory is more than the gpu memory (which is usually the case). If you remove that line, the code will load the next files into the cache only if there are more files to be loaded (self._maxpos < self.parent._maxpos). If the whole dataset fits on the GPU (self._maxpos == self.parent._maxpos), it won't do anything avoiding the overhead of moving the same data repeatedly from the main memory.

**Comment by phvu** [comment]
Thank you for your clarification, I understand the code better now.
Unfortunately in my case, I am using Debian 32bits with some freaking limits of memory that Python can take. Therefore I can only have 0.5 GB of RAM for storing data (I put "0.5G" in the data proto file), and that makes the Python process use 2GB of RAM, which is the limit. While I have > 2GB memory on GPU, this limit is a pain. And yes, unfortunately, my data can not fit on GPU or CPU memory...

Anyway in this case, do you think it is safe to workaround like that?

**Comment by nitishsrivastava** [comment]
Yes, that would be a safe work around.
