### ISSUE TITLE
what is the 'output path' mean in the running example?

### ISSUE THREAD

**Issue by qianlongzju** [nitishsrivastava/deepnet#2]
After change to deepnet/deepnet/examples, and running the following command,
$python setup_examples.py <path to mnist dataset> <output path>

I make a 'out' directory under example, and ran 
$python setup_examples.py <path to mnist dataset>  out
no file is added to the 'out' directory

**Comment by nitishsrivastava** [comment]
The setup_examples.py script takes two inputs - the location of the dataset and the directory where the learned models will be stored. It does not add files to the 'out' directory, only sets up the trainers so that when the training is done, learned models will be written into 'out'.

**Comment by qianlongzju** [comment]
Got it..I see these directories in train.pbtxt...... But,  there is another problem,,,The directory path is relative to deepnet/deepnet/examples,  so when writen into the subdirectory like rbm,,, the path need to be one more depth,,so "../" should be added to the front of the path...

**Comment by nitishsrivastava** [comment]
Using absolute paths in setup_examples.py now.
