### ISSUE TITLE
What does "shape" mean in dbn?

### ISSUE THREAD

**Issue by LastMonopoly** [nitishsrivastava/deepnet#21]
Hi nitish,

Could you kindly explain the parameter "shape" from https://github.com/nitishsrivastava/deepnet/blob/master/deepnet/examples/dbn/mnist_rbm1.pbtxt?

Thanks so much!

**Comment by nitishsrivastava** [comment]
It means that the input has shape 28 X 28. This information is not required for training. It is only used when you visualize the features.
