### ISSUE TITLE
what does "clobber" mean in multimodal_dbn

### ISSUE THREAD

**Issue by qianlongzju** [nitishsrivastava/deepnet#25]
att

**Comment by rdaniel** [comment]
It is there to allow or prevent overwriting the files produced by the various parts of the runall_dbn.sh script. If you want to re-run the model and train everything you can set clobber=True. Otherwise you have to delete all the materials produced by the scripts.

HTH,
Ron

**Comment by qianlongzju** [comment]
Thank you, Ron... Now I know its usage...
