### ISSUE TITLE
rbm example problems

### ISSUE THREAD

**Issue by sergeyplis** [nitishsrivastava/deepnet#3]
Hi Nitish,
I have successfully compiled your code following the instructions and I am trying to run the rbm example (deepnet/examples/rbm). I have two issues:
1. ./runall.sh
   Traceback (most recent call last):
   File "../../trainer.py", line 7, in <module>
     from cudamat import gpu_lock
   ImportError: cannot import name gpu_lock

Hmm! If I just fire up python and execute "from cudamat import gpu_lock" - works smoothly. So what I have done, I have just copied trainer.py into examples/rbm and edited train.pbtxt to account for the change. And not it runs but see below
1. Fails on data import, I am printing filename_list in the Get method of the datahandler and it is empty as you can see. 
   Thanks!

Train Step: 0[]
Traceback (most recent call last):
  File "trainer.py", line 56, in <module>
    main()
  File "trainer.py", line 51, in main
    model.Train()
  File "/na/homes/splis/soft/tools/deepnet/deepnet/neuralnet.py", line 463, in Train
    self.GetTrainBatch()
  File "/na/homes/splis/soft/tools/deepnet/deepnet/neuralnet.py", line 363, in GetTrainBatch
    self.GetBatch(self.train_data_handler)
  File "/na/homes/splis/soft/tools/deepnet/deepnet/dbm.py", line 229, in GetBatch
    super(DBM, self).GetBatch(handler=handler)
  File "/na/homes/splis/soft/tools/deepnet/deepnet/neuralnet.py", line 354, in GetBatch
    data_list = handler.Get()
  File "/na/homes/splis/soft/tools/deepnet/deepnet/datahandler.py", line 621, in Get
    batch = self.gpu_cache.Get(self.batchsize, get_last_piece=self.get_last_piece)
  File "/na/homes/splis/soft/tools/deepnet/deepnet/datahandler.py", line 397, in Get
    self.LoadData()
  File "/na/homes/splis/soft/tools/deepnet/deepnet/datahandler.py", line 313, in LoadData
    data_cpu = self.parent.Get(self._maxpos)
  File "/na/homes/splis/soft/tools/deepnet/deepnet/datahandler.py", line 250, in Get
    self.LoadData()
  File "/na/homes/splis/soft/tools/deepnet/deepnet/datahandler.py", line 222, in LoadData
    self.data = self.parent.Get(self._maxpos)
  File "/na/homes/splis/soft/tools/deepnet/deepnet/datahandler.py", line 65, in
Get
    current_file = (self.last_read_file[i] + 1) % num_files
ZeroDivisionError: integer division or modulo by zero

**Comment by nitishsrivastava** [comment]
Hello pliz,
To fix the first problem - make sure cudamat is on your LD_LIBRARY_PATH. See INSTALL.txt for more details.
It is failing on data import because it can't find the data. Did you download the data and run setup_examples.py ? If not, see INSTALL.txt for how to do this.

**Comment by sergeyplis** [comment]
Thanks Nitish! cudamat is on my path as I said if I run python anywhere else and just import cudamat - works smoothly, which does not solve the problem.
With the second issue - I've resolved it by looking into mnist.pbtxt and observing relative paths there, but relative to the examples directory. After changing the relative path to the absolute path - I can run the example (using my trainer.py copy method rather than your runall.sh) and it works (well, still running).

## Thanks!

Sergey

**Comment by sergeyplis** [comment]
So I've figured out the problems:
1. Before reading INSTALL.txt I've shadowed cudamat.py with a different file in the deepnet directory. Removing it - solved the first problem.
2. When running setup_examples.py I gave the script relative paths :) That created problems in issue 2.  An easy fix would be:
   <code>
   diff --git a/deepnet/examples/setup_examples.py b/deepnet/examples/setup_examples.py
   index e23fee5..136ba43 100644
   --- a/deepnet/examples/setup_examples.py
   +++ b/deepnet/examples/setup_examples.py
   @@ -37,8 +37,8 @@ def MakeModels(model_file, output_path):
      util.WritePbtxt(model_file, model)
   
    def main():
   -  data_path = sys.argv[1]  # Path to mnist data directory.
   -  output_path = sys.argv[2]  # Path where learned models will be written.
   -  data_path = os.path.abspath(sys.argv[1]) # Path to mnist data directory.
   -  output_path = os.path.abspath(sys.argv[2]) # Path where learned models will be written.
     
     data_pbtxt_file = os.path.join(data_path, 'mnist.pbtxt')
     MakeDataPbtxt(data_pbtxt_file, data_path)
     </code>
     
     ## Thanks!
     
     Sergey

**Comment by nitishsrivastava** [comment]
Thanks for the suggestion. I have added abspath in a new commit.
