### ISSUE TITLE
What is the difference between "compute_sparsity" in a hidden layer and "sparsity" in hyperparams?

### ISSUE THREAD

**Issue by nian-liu** [nitishsrivastava/deepnet#39]
I found in some "model.pbtxt" files, for example, model.pbtxt in mnist rbm model example, there are two kinds of parameters related with  sparsity, one called "compute_sparsity" in the field "layer", and another called "sparsity" in the field "hyperparams". Sometimes the two parameters contradict with each other, usually compute_sparsity=true but sparsity=false, this really confused me. What is the difference between them?

**Comment by nitishsrivastava** [comment]
"compute_sparsity = True" means that the sparsity of that hidden layer will be computed.
"sparsity = True" means that sparsity will be enforced as a regularization term.

**Comment by nian-liu** [comment]
Hi Nitish,
    Thanks for your help. But I still have a question. In the situation where "sparsity = False" and "compute_sparsity = True", if wen don't want a sparsity regularization term, what is the usage of  the computed sparsity of the hidden layer?

**Comment by nitishsrivastava** [comment]
Sometimes it is informative to know what kind of sparsity is being achieved without any additional regularization. For example, you can compare this to what sparsity you get with regularization and see what difference the regularization made.

**Comment by nian-liu** [comment]
Hi Nitish,
    I studied the python code and found that only "sparsity" equaled "True", "perf.sparsity" would be calculated in "dbm.py". I didn't found where "compute_sparsity" worked. Maybe that's my fault caz I'm a fresh man with python. Any way, thank you for your help.
