### ISSUE TITLE
libeigenmat.so: cannot open shared object file

### ISSUE THREAD

**Issue by reudismam** [nitishsrivastava/deepnet#40]
I'm getting this error when running ./runall.sh 

<module>
    _eigenmat = ct.cdll.LoadLibrary('libeigenmat.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: libeigenmat.so: cannot open shared object file: No such file or directory

**Comment by reudismam** [comment]
It was resolved when I installed Cuda.

**Comment by ghost** [comment]
How did you install CUDA?

**Comment by a-taherkhani** [comment]
reducing the gpu_mem in runall_dbn.sh might solve it.Also run the make file in cudamat dir.
