### ISSUE TITLE
No GPU board available

### ISSUE THREAD

**Issue by Robert0812** [nitishsrivastava/deepnet#45]
I can run ./runall.sh under /example/rbm successfully at the first time, and my GPU works normally. However, there is an error on the print function due to python version incompatibility I think. After that, when I run the example again, it is terminated with a message "No GPU board available."  

I seems that the code locked my GPU last time, and it didn't free it. How can I unlock my GPU?

**Comment by Robert0812** [comment]
The GPU can be unlocked by rebooting the system

**Comment by YS-L** [comment]
Instead of rebooting the system, an easier way is to run `gpu_lock.py` (provided in the cudamat directory) as a script, passing in the option of `--free <id>` to free the concerned GPU board.

**Comment by Rietaros** [comment]
I'm using CUDA 7.5 nvidia 352..39.

And have the same problem.
While I run gpu_lock.py --id it comes with output -1

Any suggestion?
