### ISSUE TITLE
no field named "mcmc_steps" and "lower_model" when running multimodal_dbm example

### ISSUE THREAD

**Issue by nian-liu** [nitishsrivastava/deepnet#50]
hi nitish srivastava,
    I have problems when running multimodal_dbm example, the error messages are:
google.protobuf.text_format.ParseError: 17:3 : Message type "deepnet.Hyperparams" has no field named "mcmc_steps".

google.protobuf.text_format.ParseError: 23:1 : Message type "deepnet.Model" has no field named "lower_model".

  It seems that the multimodal_dbm example are not completely compatible with deepnet. 

By the way, if I want to use dropout in multimodal_dbm, specifically I want to use dropout_prob=0.2 for image input layer and dropout_prob=0.5 for image hidden1 layer and hidden2 layer , is it correct that I use dropout for image hidden1 layer both in running image rbm1 and image rbm2? Or I should just use dropout for the visible layer in each rbm?

**Comment by YusukeO** [comment]
Hi, nian
Did multimodal_dbm work? 
If so, please share how you solve mcmc problem. I'm longing it!

Thank you very much!
