### ISSUE TITLE
Data format for training different models

### ISSUE THREAD

**Issue by sharathchandra92** [nitishsrivastava/deepnet#52]
Hi,

I would like to know if the data format used by your model is same as that used by cuda-convnet?
I am dealing with different types of data, so wanted to know if there is any function which is pre-built to conver this data into the type compatible with different models.

Let me know.

Thanks.

**Comment by parthg** [comment]
Hi, 

Any update on this?

Thanks.

**Comment by nian-liu** [comment]
Hi Sharath,
      You can download and extract the MNIST dataset from http://www.cs.toronto.edu/~nitish/deepnet/mnist.tar.gz , and study the data format of this example carefully. Or you can do as below:
       First, you should transfer your sample matrices into proper form, which means 2-D matrices, one sample in a row, one pixel in a  column, for example, if your image is of size 8_8, and you have 100 training images, then you should have a sample matrix of size 100_64, so do the label matrices; 
       Next, you should transfer the .mat files into python compatible format—— .npy files. For example, I got a matlab sample file named fmri.mat, which has the form mentioned above, then I should use the commands below in a python command window (console):

import scipy.io as sio
data=sio.loadmat('fmri.mat')
data=data['fmri']
data=data.astype('float32')
np.save('fmri.npy',data)

```
  Make sure that your .mat files are in the python working directory. Maybe you should install the scipy packet in your system.
  For my atypical English, you can ask me if you have any questions.
```

**Comment by sharathchandra92** [comment]
@nian-liu Thanks a lot for your answer. 
Can we share our mail ID - I have a few questions and would like to get some clarifications from you, as you are more experienced in using this module.
My ID is sharathchandra92@gmail.com
Please send me a mail.
Thanks :)
