### ISSUE TITLE
How to  configure sharing weights in deepnet?

### ISSUE THREAD

**Issue by nian-liu** [nitishsrivastava/deepnet#53]
Hi nitish,
   I wanna use sharing weights in some edges in deep models, could you public some examples about it, or just tell me how to configure it in pbtxt files? Thanks in advance.

**Comment by sharathchandra92** [comment]
Hi nian-liu, sorry to interrupt your question with another question, but was curious if you know what is the input format that deepnet would take?
That is I have .mat files of several grayscale images with their classes. How do I transform this?
Please let me know. Thanks :)

I posted this as a separate question, but got no response, so, just wanted to take your help.

**Comment by nitishsrivastava** [comment]
@nian-liu I don't have an example setup for it, but take a look at message Edge in protos/deepnet.proto. Fields 12-15 can be used to specify whether the edge weight is tied, which pair of nodes it is tied to, and whether it is tied to the transpose of that edge weight.

**Comment by nian-liu** [comment]
@nitishsrivastava Thank you for your kind heart, I have figured that question out. It seems that deepnet.proto is  very useful!

**Comment by nian-liu** [comment]
@nitishsrivastava  Another question: If I wanna use RGB images as inputs, I should flatten every image matrix into a vector as a sample, when I  flatten RGB image matrices, what is the order of the 3 dimensions—— height, width and the number of color channel? This makes great sense when using CNN or visualizing the learned weights.
