### ISSUE TITLE
segfault in dbn example

### ISSUE THREAD

**Issue by sergeyplis** [nitishsrivastava/deepnet#6]
Hi Nitish,
I've run the dbn example over the weekend and it segfaulted on running Classifier. Here is the output:
./runall.sh: line 11: 15313 Segmentation fault      (core dumped) ${train_deepnet} mnist_classifier.pbtxt train_classifier.pbtxt eval.pbtxt

real    3191m57.396s
user    3186m10.271s
sys     1m33.154s

And this is after 2 days of crunching :) Good all checkpoints are saved.
## Thanks!

Sergey

**Comment by nitishsrivastava** [comment]
Hi Sergey,
Does this happen after the classifier has run for a while or just at the beginning ?

**Comment by sergeyplis** [comment]
It happens after it has finished I believe. It ran for 1000000 steps and here are its last words:
Step 1000000  T_sp: 0.307 T_sp: 0.309 T_sp: 0.149 T_CE: 0.623 T_Acc: 0.807 (80668/100000) E_sp: 0.306 E_sp: 0.309 E_sp: 0.149 E_CE: 0.445 E_Acc: 0.884 (8842/10000)
Writing checkpoint mnist_classifier_pretrained_1361765543
./runall.sh: line 11: 15313 Segmentation fault      (core dumped) ${train_deepnet} mnist_classifier.pbtxt train_classifier.pbtxt eval.pbtxt

**Comment by nitishsrivastava** [comment]
In that case, just ignore that seg fault. The program has completed doing everything it was meant to do. This happens due to a relatively harmless bug in the cudamat destructor.

**Comment by sergeyplis** [comment]
Great! I am just checking. There is no way yet for me to use these results as I have not read trough all of the code to find out how :)
Thanks!

**Comment by qianlongzju** [comment]
I have encountered similar situation several times.
Sometimes, it happened when it had not finished....
I just rerun until the program finished successfully...
