### ISSUE TITLE
Computing prediction probabilities

### ISSUE THREAD

**Issue by daquang** [nitishsrivastava/deepnet#63]
Is it possible to get deepnet to output the prediction probabilities for each sample in a test dataset for a given model's parameters? I am doing some ROC analysis and it would be great if I could get the probability for each class for each sample. Then, I could just vary the p-value threshold to generate my ROC curves. Does anyone know of a way to do this with deepnet?

**Comment by daquang** [comment]
Figured it out. Had to hack some of the scripts a little to give me the proper output.

**Comment by ghost** [comment]
@daquang Could you explain it a little? I have this question these days.
