### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by tengshaofeng** [nitishsrivastava/deepnet#77]
hi,nitishsrivastava
       when i run the example of multimodal_dbn ,after the output message ''Collecting all representations",there is a problem like this:

Output written in directory /home/tbq/Downloads/flickr/dbn_reps/split_1
Output written in directory /home/tbq/Downloads/flickr/dbn_reps/split_2
Output written in directory /home/tbq/Downloads/flickr/dbn_reps/split_3
Split 1 image_input
Step 500  T_CE: 13.450Traceback (most recent call last):
  File "/home/tbq/Downloads/deepnet-master/deepnet/trainer.py", line 60, in <module>
    main()
  File "/home/tbq/Downloads/deepnet-master/deepnet/trainer.py", line 54, in main
    model.Train()
  File "/home/tbq/Downloads/deepnet-master/deepnet/neuralnet.py", line 649, in Train
    self.Evaluate(validation=True, collect_predictions=collect_predictions)
  File "/home/tbq/Downloads/deepnet-master/deepnet/neuralnet.py", line 394, in Evaluate
    MAP, prec50, MAP_list, prec50_list = self.ComputeScore(predictions, targets)
  File "/home/tbq/Downloads/deepnet-master/deepnet/neuralnet.py", line 429, in ComputeScore
    this_ap, this_prec = self.ScoreOneLabel(preds[:,i], targets[:,i])
  File "/home/tbq/Downloads/deepnet-master/deepnet/neuralnet.py", line 409, in ScoreOneLabel
    targets_sorted = targets[(-preds.T).argsort().flatten(),:]
IndexError: too many indices for array

what i should do?

**Comment by Kyung-Min** [comment]
Try this 
targets_sorted = targets[(-preds.T).argsort().flatten()]
instead of using
targets_sorted = targets[(-preds.T).argsort().flatten(),:]

**Comment by tengshaofeng** [comment]
thanks very much.i will try later------------------ 原始邮件 ------------------
发件人: "notifications"notifications@github.com
发送时间: 2014年11月3日(星期一) 晚上9:36
收件人: "nitishsrivastava/deepnet"deepnet@noreply.github.com;
抄送: "tengshaofeng"307149416@qq.com;
主题: Re: [deepnet] IndexError: too many indices for array (#77)

Try this 
 targets_sorted = targets[(-preds.T).argsort().flatten()]
 instead of using
 targets_sorted = targets[(-preds.T).argsort().flatten(),:]

&mdash;

**Comment by jnhwkim** [comment]
@Kyung-Min @tengshaofeng It works for me.

**Comment by hoffmast** [comment]
It worked for me as well. Thank you!

**Comment by YusukeO** [comment]
It works for me. Thank you!
