### ISSUE TITLE
DBM pretraining issue

### ISSUE THREAD

**Issue by STZhang** [nitishsrivastava/deepnet#84]
I am really interested in your work 'Multimodal learning with deep boltzmann machine' and I have read your deepnet code. 
    When learning the parameters of the first layer DBM, the bottom-up weights are constrained to be twice the top-down weights. But I have trouble finding the parameter that related to "twice" or the function to copy the input nodes. Would you mind helping me with this? 
     Sorry for the trouble and Thanks a lot for your help.

**Comment by sanggeol** [comment]
edge up_factor might be what you're looking for.

**Comment by hoffmast** [comment]
@STZhang , were you able to create a script to train a multimodal DBM, such as something similar to the runall_dbn.sh script used to train and test the multimodal DBN example? If so, would you be able/willing to provide the script you used or describe how to best create one?

Thank you in advance for any help you can provide.
