### ISSUE TITLE
multimodal_dbn

### ISSUE THREAD

**Issue by qianlongzju** [nitishsrivastava/deepnet#9]
Hi, nitish,
    I am testing multimodal_dbn, and encountered an error..
    It says: AttributeError: /home/qianlong/deepnet/cudamat/libcudamat.so: undefined symbol: perturb_prob
    Need I recompile cudamat ?
    See the pic  if it can provide any information...

![err1](https://f.cloud.github.com/assets/769655/243975/bf1a08b0-8a59-11e2-9384-b7a672546f12.PNG)

**Comment by nitishsrivastava** [comment]
Yes please recompile cudamat. Just type 'make' in the cudamat directory.

**Comment by qianlongzju** [comment]
After recompiling cudamat, multimodal_dbn model training completes successfully.  
Thank you for your help.

**Comment by nitishsrivastava** [comment]
That's great!
